analýza dat z MARASTu
cvut/MI-PYT pull request #59
Opened 2016-11-27 08:41 UTC by kalvotom

Návrh zadání.

2016-11-27 10:35 UTC, hroncok requested changes

2016-11-27 10:35 UTC, hroncok commented on tutorials/13_semestralka.md
> +odpovídat zablokována.
přidal bych "na nějakou dobu"

2016-11-27 10:35 UTC, hroncok commented on tutorials/13_semestralka.md
> +přemýšlí nad otázkou ale i tak odpovídají špatně, atp.). Lze si vymyslet
čárky kolem "co dlouho￼+přemýšlí nad otázkou"

2016-11-27 10:35 UTC, hroncok commented on tutorials/13_semestralka.md
> +Při řešení je možné využít například [pandas](http://pandas.pydata.org),
Z pohledu MI-PYT je použití Pandas podmínkou.

2016-11-27 10:35 UTC, hroncok commented on tutorials/13_semestralka.md
> +[kalvotom](http://github/kalvotom) ve formátu CSV, případně v jiném vhodném.
I studentovi pomůžeš s tím, co se po něm chce?

2016-11-27 12:08 UTC, jirutka commented on tutorials/13_semestralka.md
> +Při řešení je možné využít například [pandas](http://pandas.pydata.org),
Because…?

![bd8003add79f5d11643d53abc4dc83aeb0c9dbf060a49c0f055cd18ea41909ef](https://cloud.githubusercontent.com/assets/949228/20648274/8d54b6d2-b4a2-11e6-8e20-82b317aa1316.jpg)

2016-11-27 16:23 UTC, hroncok commented on tutorials/13_semestralka.md
> +Při řešení je možné využít například [pandas](http://pandas.pydata.org),
Protože semestrálka musí navazovat na nějaké probírané téma.

2016-11-28 20:15 UTC, kalvotom commented on tutorials/13_semestralka.md
> +odpovídat zablokována.
OK.

2016-11-28 20:17 UTC, kalvotom commented on tutorials/13_semestralka.md
> +přemýšlí nad otázkou ale i tak odpovídají špatně, atp.). Lze si vymyslet
Dobře.

2016-11-28 20:18 UTC, kalvotom commented on tutorials/13_semestralka.md
> +Při řešení je možné využít například [pandas](http://pandas.pydata.org),
Rozumím, zdůrazním to.

2016-11-28 20:56 UTC, kalvotom commented on tutorials/13_semestralka.md
> +[kalvotom](http://github/kalvotom) ve formátu CSV, případně v jiném vhodném.
Určitě, s tím počítám.

2016-11-28 21:15 UTC, kalvotom commented
Zkusil jsem to lehce upřesnit.

2016-11-29 00:06 UTC, hroncok commented on tutorials/13_semestralka.md
> +jaké experimenty provést. V dalším průběhu [kalvotom](http:github/kalvotom)
Link je divný...

2016-11-29 00:08 UTC, merged